version: 2.1
orbs:
  continuation: circleci/continuation@0.1.2

defaults: &defaults
  working_directory: /tmp/cci-test

jobs: # basic units of work in a run
  build:
    <<: *defaults
    docker: # use the Docker executor
      # CircleCI Node images available at: https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to setup an environment variable
      # Redirect MY_ENV_VAR into $BASH_ENV
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="FOO"' >> "$BASH_ENV"
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - run:
          name: "Print an env var stored in the Project"
          command: echo ${PROJECT_ENV_VAR}
      - run:
          name: "Print an env var stored in a Context"
          command: echo ${CONTEXT_ENV_VAR}
      - run: echo "export MY_ENV_VAR=$MY_ENV_VAR" >> workspace/new-env-vars
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars
  test:
    <<: *defaults
    executor: continuation/default
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - checkout
      - run:
          shell: /bin/sh
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}

workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: Testing-Env-Vars
      - test:
          requires:
            - build